#!/usr/bin/env python3
"""Emit a reading as JSON - the contract your app renders against.

Nothing here is generated by a language model: every line is the output of a named rule with a named
source, so the app can show "why" and the user can audit it. Optional prose (a friendly voice) belongs
in the app layer, on top of this - never inside it.

Usage:
  python3 engine/export_reading.py --mothers "Carcer,Amissio,Caput Draconis,Populus" \
      --topic travel_journey --day Wednesday --hour 4 --out reading.json
"""
import argparse, json, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import deep_read as dr

SCHEMA_VERSION = "1.0"

def reading(mothers, topic, day=None, hour=None, night=False):
    c = dr.build(mothers)
    H = c["houses"]
    out = {
      "schema": SCHEMA_VERSION,
      "input": {"mothers": mothers, "topic": topic, "day": day, "planetary_hour": hour, "night": night},
      "chart": [{"house": dr.ROMAN[i], "figure": dr.fig(H[i]), "pattern": H[i],
                 "points": sum(H[i])} for i in range(16)],
      "court": {"right_witness": dr.fig(H[12]), "left_witness": dr.fig(H[13]),
                "judge": dr.fig(H[14]), "judge_points": sum(H[14]),
                "sentence": dr.fig(H[15]),
                "sentence_rule": "XV + Mother I (al-Zanati: 'from the first and the fifteenth')"},
      "validity": [{"flag": k, "note": v} for k, v in dr.validity(c)],
      "relations": {
        "motus": {f: hs for f, hs in dr.motus(c).items()},
        "parentage": [{"house": dr.ROMAN[h - 1],
                       "parents": ({"kind": "transposition", "note": v} if ps is None else
                                   {"kind": "sum",
                                    "from": [dr.ROMAN[ps[0] - 1], dr.ROMAN[ps[1] - 1]],
                                    "figures": list(v)}),
                       "tone": tone}
                      for h, ps, v, tone in dr.parentage(c)],
      },
      "trace": {},
      "specifics": {},
      "cross_read": dr.crossread(c),
      "provenance_keys": list(dr.FIG.keys()),
      "flags": [],
    }
    path, br, ends = dr.via_puncti(c)
    out["trace"]["via_puncti"] = {"path": [{"house": r, "figure": f} for r, f in path],
                                 "branches": br,
                                 "branch_count": max(1, len(ends)),
                                 "endpoints": [{"house": h, "figure": f, "kind": k} for h, f, k in ends],
                                 "formed": len(path) > 1,
                                 "rule": "follow the Judge's head line upward to the parent that matches"}
    s, rem, rf, tot, rem2, rf2 = dr.projection(c)
    out["trace"]["projection_of_points"] = {"single_dots": s, "house": dr.ROMAN[rem-1], "figure": rf}
    out["trace"]["part_of_fortune"] = {"total_points": tot, "house": dr.ROMAN[rem2-1], "figure": rf2}
    gd, cal = dr.triplicities(c, topic)
    out["relations"]["triplicities"] = {"golden_dawn": gd, "calatarama_routing": cal}
    p = dr.perfection(c, topic)
    out["relations"]["perfection"] = p
    try:
        pr = json.loads((dr.HERE.parent / "kb" / "perfection_priors.json").read_text())["priors"]
        share = next((v["pct"] for k, v in pr.get(f"question_in_house_{dr.ROMAN[p['houses'][1]-1]}", {})
                      .items() if k.startswith(p["mode"].lower()[:6])), None)
        if share is not None:
            out["relations"]["perfection"]["base_rate_pct"] = share
            out["relations"]["perfection"]["news_value"] = (
                "newsworthy" if share < 8 else "ordinary" if share < 40 else "default - weak evidence")
    except Exception as e:
        out["flags"].append(f"priors unavailable: {e}")
    hum, ex, cure = dr.humours(c, topic)
    out["specifics"]["constitution"] = {"tally": hum, "excess": ex, "remedy_reads_as": cure}
    out["specifics"]["who"] = dr.who(c, topic)
    out["specifics"]["where"] = dr.where(c, topic)
    out["specifics"]["when"] = dr.when(c, topic)
    try:
        import elections as EL
        v, det = EL.gate(H, day, hour, night)
        out["validity"].append({"flag": f"planetary_gate:{v}", "note": det})
        out["validity"].append({"flag": "recast_options",
                                "note": [{"day": d, "lord": pn, "hits": len(h)}
                                         for d, pn, h in EL.best_alternatives(H)]})
    except Exception as e:
        out["flags"].append(f"elections unavailable: {e}")
    try:
        import questions as QS
        qs = {}
        for k in QS.TOPIC_ALIAS.get(topic, []):
            a = QS.answer(c, k)
            qs[k] = {"rule": a["rule"], "leaf": a["leaf"], "call": a["call"],
                     "consult": a["consult"], "angles": a["angles"]}
            for extra in ("turned_chart", "tiebreak", "extracta_IV_V", "between",
                          "forbidden_figures", "life_passage"):
                if extra in a: qs[k][extra] = a[extra]
        out["sub_questions"] = qs
        if not qs:
            out["flags"].append(f"topic {topic!r} has no sub-question bank entry - the answer is the "
                               f"general judgement only; add the topic to engine/questions.py TOPIC_ALIAS"
                               + ("" if topic in QS.TOPIC_ALIAS else " (unknown topic)"))
    except Exception as e:
        out["flags"].append(f"question engine unavailable: {e}")
    # name every unfilled slot, so the app renders an honest blank instead of a confident one
    gaps = []
    for slot in ("who", "where", "when"):
        d = out["specifics"].get(slot) or {}
        items = d.values() if isinstance(d, dict) and all(isinstance(x, dict) for x in d.values()) else [d]
        for it in items:
            if not isinstance(it, dict):
                continue
            for k, val in it.items():
                if val in (None, "", "—") and k not in ("_gap", "gap"):
                    gaps.append(f"{slot}.{k}: not in the extracted source table")
    if "gap" in (out["specifics"].get("where") or {}) and out["specifics"]["where"]["gap"]:
        gaps.append("where: " + out["specifics"]["where"]["gap"])
    out["gaps"] = sorted(set(gaps))[:24]
    # one object the UI can render before it understands anything else
    perf = out["relations"].get("perfection") or {}
    gate = next((v["flag"].split(":", 1)[1] for v in out["validity"]
                 if str(v.get("flag", "")).startswith("planetary_gate:")), None)
    blockers = [v["flag"] for v in out["validity"]
                 if v.get("flag") in {"RECAST", "DISTRUST", "SUSPEND", "ERROR"}]
    mode = str(perf.get("mode", ""))
    out["verdict"] = {
        "does_it_perfect": ("yes" if mode.lower().startswith("occupation") else
                            "no" if (not mode or mode.lower().startswith("no")) else "qualified"),
        "mode": perf.get("mode"), "base_rate_pct": perf.get("base_rate_pct"),
        "news_value": perf.get("news_value"), "judge": out["court"]["judge"],
        "sentence": out["court"]["sentence"], "blockers": blockers, "planetary_gate": gate,
        "headline": perf.get("verdict"),
        "trace_heads": max(1, len(out["trace"]["via_puncti"].get("endpoints") or [])),
    }
    out["flags"].append("labels marked with * (Puer/Puella) are contested between traditions")
    return out

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--mothers", default="Carcer,Amissio,Caput Draconis,Populus")
    ap.add_argument("--topic", default="travel_journey")
    ap.add_argument("--day", default=None); ap.add_argument("--hour", type=int, default=None)
    ap.add_argument("--night", action="store_true")
    ap.add_argument("--out", default="-")
    a = ap.parse_args()
    js = json.dumps(reading([dr.norm(x) for x in a.mothers.split(",")], a.topic,
                           a.day, a.hour, a.night), indent=1, ensure_ascii=False)
    if a.out == "-":
        print(js)
    else:
        pathlib.Path(a.out).write_text(js); print("wrote", a.out, len(js), "bytes")
