// generated by library/tools/gen_types.py - the reading contract for TS/Swift apps
// Source of truth: library/schema/*.json. Regenerate with `make types`.

/** generated from library/schema/grounded_reading.json - do not edit */

export interface Grounded geomancy reading {
  schema: unknown;
  topic?: string | null;
  quesited_house?: number | null;
  chart?: Grounded geomancy readingChart;
  court?: Grounded geomancy readingCourt;
  claims: (Grounded geomancy readingClaimsItem)[];
  method?: (Grounded geomancy readingMethodItem)[];
  citations: Grounded geomancy readingCitations;
  gaps?: Grounded geomancy readingGaps;
  audit?: Grounded geomancy readingAudit;
  standing: string;
}

export interface Grounded geomancy readingChart {
  [key: string]: string;
}

export interface Grounded geomancy readingCourt {
  [key: string]: unknown;
}

export interface Grounded geomancy readingClaimsItem {
  type: "sourced_ruling" | "sources_disagree" | "figure_quality" | "correspondence" | "look_rule" | "no_source_ruling" | "method_note";
  mode?: "quote" | "gloss";
  figure?: string | null;
  house?: number | null;
  text: string;
  leans?: string[];
  cites: Grounded geomancy readingClaimsItemCites;
  validate_rule?: string;
}

export interface Grounded geomancy readingClaimsItemCites {
  voice_ids: string[];
  n_voices?: number;
  works?: string[];
}

export interface Grounded geomancy readingMethodItem {
  [key: string]: unknown;
}

export interface Grounded geomancy readingCitations {
  [key: string]: Grounded geomancy readingCitationsValue;
}

export interface Grounded geomancy readingCitationsValue {
  authority: string;
  through?: string;
  year?: number | null;
  locator: string | null;
  licence?: string | null;
  cite_only?: boolean;
}

export interface Grounded geomancy readingGaps {
  [key: string]: unknown;
}

export interface Grounded geomancy readingAudit {
  [key: string]: unknown;
}

/** generated from library/schema/manifest.json - do not edit */

export interface Manifest {
  dataset: string;
  version?: string;
  generated: string;
  counts: ManifestCounts;
  fts5?: boolean;
  licence_summary: ManifestLicenceSummary;
  build_warnings?: unknown[];
  files: ManifestFiles;
}

export interface ManifestCounts {
  [key: string]: unknown;
}

export interface ManifestLicenceSummary {
  full_text_sources: string[];
  cite_only_sources: string[];
  never_used?: string[];
}

export interface ManifestFiles {
  [key: string]: unknown;
}

/** generated from library/schema/passage.json - do not edit */

export interface A passage in the library: text is never allowed without provenance {
  work: string;
  kind: string;
  figure?: string | null;
  house?: string | number | null;
  locator: string;
  text: string;
  confidence: string;
}

/** generated from library/schema/reading.json - do not edit */

export interface Geomancy reading (deterministic engine output) {
  schema: unknown;
  input: Geomancy reading (deterministic engine output)Input;
  chart: (Geomancy reading (deterministic engine output)ChartItem)[];
  court: Geomancy reading (deterministic engine output)Court;
  validity: (Geomancy reading (deterministic engine output)ValidityItem)[];
  relations: Geomancy reading (deterministic engine output)Relations;
  trace: Geomancy reading (deterministic engine output)Trace;
  specifics: Geomancy reading (deterministic engine output)Specifics;
  sub_questions?: Geomancy reading (deterministic engine output)SubQuestions;
  cross_read?: Geomancy reading (deterministic engine output)CrossRead;
  gaps: string[];
  flags: string[];
  verdict: Geomancy reading (deterministic engine output)Verdict;
}

/** generated from library/schema/rule.json - do not edit */

export interface Rule {
  id: string;
  name?: string;
  answers?: string | null;
  conf: "HIGH" | "MED" | "LOW";
  status?: "NAMED_ONLY" | "IMPLEMENTED";
  source: string;
  procedure?: string;
  test_case?: RuleTestCase;
  notes?: string | unknown | null;
}

export interface RuleTestCase {
  [key: string]: unknown;
}
