// generated by library/tools/gen_types.py - the reading contract for TS/Swift apps
// Source of truth: library/schema/*.json. Regenerate with `make types`.

/** generated from library/schema/grounded_reading.json - do not edit.
 * Grounded geomancy reading
 */

export interface GroundedReading {
  schema: unknown;
  topic?: string | null;
  quesited_house?: number | null;
  chart?: GroundedReadingChart;
  court?: GroundedReadingCourt;
  claims: GroundedReadingClaimsItem[];
  method?: GroundedReadingMethodItem[];
  citations: GroundedReadingCitations;
  gaps?: GroundedReadingGaps;
  audit?: GroundedReadingAudit;
  standing: string;
}

export interface GroundedReadingChart {
  [key: string]: string;
}

export interface GroundedReadingCourt {
  [key: string]: unknown;
}

export interface GroundedReadingClaimsItem {
  type: "sourced_ruling" | "sources_disagree" | "figure_quality" | "correspondence" | "look_rule" | "no_source_ruling" | "method_note";
  mode?: "quote" | "gloss";
  figure?: string | null;
  house?: number | null;
  text: string;
  leans?: string[];
  cites: GroundedReadingClaimsItemCites;
  validate_rule?: string;
}

export interface GroundedReadingClaimsItemCites {
  voice_ids: string[];
  n_voices?: number;
  works?: string[];
}

export interface GroundedReadingMethodItem {
  [key: string]: unknown;
}

export interface GroundedReadingCitations {
  [key: string]: GroundedReadingCitationsValue;
}

export interface GroundedReadingCitationsValue {
  authority: string;
  through?: string;
  year?: number | null;
  locator: string | null;
  licence?: string | null;
  cite_only?: boolean;
}

export interface GroundedReadingGaps {
  [key: string]: unknown;
}

export interface GroundedReadingAudit {
  [key: string]: unknown;
}

/** generated from library/schema/manifest.json - do not edit.
 * Manifest
 */

export interface Manifest {
  dataset: string;
  version?: string;
  generated: string;
  counts: ManifestCounts;
  fts5?: boolean;
  licence_summary: ManifestLicenceSummary;
  build_warnings?: unknown[];
  files: ManifestFiles;
}

export interface ManifestCounts {
  [key: string]: unknown;
}

export interface ManifestLicenceSummary {
  full_text_sources: string[];
  cite_only_sources: string[];
  never_used?: string[];
}

export interface ManifestFiles {
  [key: string]: unknown;
}

/** generated from library/schema/outcome_row.json - do not edit.
 * Outcome Row
 */

export interface OutcomeRow {
  always_read: unknown[];
  base_rates: OutcomeRowBaseRates;
  cal_scope: string;
  coverage_note: string;
  disagreeing_keys: unknown[];
  extra_houses: unknown[];
  label: string;
  latin: string;
  n_disagreements: number;
  n_passages_for_house: number;
  n_voice_keys: number;
  n_voices: number;
  n_works: number;
  outcome: string;
  passages: unknown[];
  priors_key: string;
  quesited_house: number;
  quesited_roman: string;
  quote_available: number;
  ruling_table: OutcomeRowRulingTable;
  significator_rules: unknown[];
  triplicities: unknown[];
  voice_keys: unknown[];
  voices: unknown[];
  works: unknown[];
}

export interface OutcomeRowBaseRates {
  [key: string]: unknown;
}

export interface OutcomeRowRulingTable {
  [key: string]: unknown;
}

/** generated from library/schema/passage.json - do not edit.
 * A passage in the library: text is never allowed without provenance
 */

export interface Passage {
  work: string;
  kind: string;
  figure?: string | null;
  house?: string | number | null;
  locator: string;
  text: string;
  confidence: string;
}

/** generated from library/schema/reading.json - do not edit.
 * Geomancy reading (deterministic engine output)
 */

export interface Reading {
  schema: unknown;
  input: ReadingInput;
  chart: ReadingChartItem[];
  court: ReadingCourt;
  validity: ReadingValidityItem[];
  relations: ReadingRelations;
  trace: ReadingTrace;
  specifics: ReadingSpecifics;
  sub_questions?: ReadingSubQuestions;
  cross_read?: ReadingCrossRead;
  gaps: string[];
  flags: string[];
  verdict: ReadingVerdict;
}

export interface ReadingInput {
  mothers: string[];
  topic: string;
  day?: string | null;
  planetary_hour?: number | null;
  night?: boolean;
}

export interface ReadingChartItem {
  house: string;
  figure: string;
  pattern: (1 | 2)[];
  points: number;
}

export interface ReadingCourt {
  judge: string;
  judge_points?: number;
  sentence: string;
  sentence_rule: string;
}

export interface ReadingValidityItem {
  [key: string]: unknown;
}

export interface ReadingRelations {
  perfection: ReadingRelationsPerfection;
  parentage?: ReadingRelationsParentageItem[];
}

export interface ReadingRelationsPerfection {
  mode: string;
  verdict: string;
  base_rate_pct?: number;
  news_value?: "newsworthy" | "ordinary" | "default - weak evidence";
  degenerate?: boolean;
}

export interface ReadingRelationsParentageItem {
  parents: ReadingRelationsParentageItemParents;
}

export interface ReadingRelationsParentageItemParents {
  [key: string]: unknown;
}

export interface ReadingTrace {
  via_puncti: ReadingTraceViaPuncti;
}

export interface ReadingTraceViaPuncti {
  path: ReadingTraceViaPunctiPathItem[];
  branches?: unknown[];
  formed: boolean;
  endpoints: ReadingTraceViaPunctiEndpointsItem[];
  branch_count?: number;
}

export interface ReadingTraceViaPunctiPathItem {
  [key: string]: unknown;
}

export interface ReadingTraceViaPunctiEndpointsItem {
  house: number;
  figure: string;
  kind: "root" | "died";
}

export interface ReadingSpecifics {
  [key: string]: unknown;
}

export interface ReadingSubQuestions {
  [key: string]: ReadingSubQuestionsValue;
}

export interface ReadingSubQuestionsValue {
  leaf: number;
  rule: string;
  call: string;
}

export interface ReadingCrossRead {
  [key: string]: unknown;
}

export interface ReadingVerdict {
  does_it_perfect: "yes" | "no" | "qualified";
  mode?: string | null;
  base_rate_pct?: number | null;
  news_value?: string | null;
  judge: string;
  sentence: string;
  blockers?: string[];
  planetary_gate?: string | null;
  headline?: string | null;
  trace_heads?: number;
}

/** generated from library/schema/rule.json - do not edit.
 * Rule
 */

export interface Rule {
  id: string;
  name?: string;
  answers?: string | null;
  conf: "HIGH" | "MED" | "LOW";
  status?: "NAMED_ONLY" | "IMPLEMENTED";
  source: string;
  procedure?: string;
  test_case?: RuleTestCase;
  notes?: string | unknown | null;
}

export interface RuleTestCase {
  [key: string]: unknown;
}
