#!/usr/bin/env python3
"""Assemble what goes inside the APK - from the app folder, never from a copy of it.

The shell must not hold its own version of the phone app. If it did, the page the browser is served and the page
the phone runs would drift, and every test in app/check_render.py would be testing something nobody installs. So
this script is the only way assets get into the build, and the check gate fails the repo outright if a hand-made
copy ever appears under android/.

Usage
    python3 android/prepare.py <build-dir>      # write <build-dir>/www and <build-dir>/res
    python3 android/prepare.py --check          # report what the build would carry, and any drift
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
APP = ROOT / "app"

# The page fetches some of these by name; the ones it does not are here so that a future link cannot 404 on a
# phone, where there is no server to fall back to and no console to look in.
WWW = ["mobile.html", "icon-192.png", "icon-512.png", "manifest.webmanifest", "sw.js"]

# one file, five buckets: the launcher scales it rather than stretching it
ICON_SIZES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192, "anydpi": 512}


def www_pairs() -> list[tuple[Path, str]]:
    return [(APP / name, name) for name in WWW]


def render_icons(res: Path) -> list[str]:
    """Launcher icons drawn by app/make_icons.py, at the size each density bucket expects.

    Deliberately not committed: a second copy of a picture someone once generated is unauditable, and here the
    drawing is twelve lines of dot arithmetic that also happen to be the first four figures of every chart.
    """
    sys.path.insert(0, str(APP))
    import make_icons  # noqa: E402

    written = []
    for bucket, px in ICON_SIZES.items():
        d = res / f"mipmap-{bucket}"
        d.mkdir(parents=True, exist_ok=True)
        (d / "ic_launcher.png").write_bytes(make_icons.png(px, px, make_icons.render(px)))
        written.append(f"mipmap-{bucket}/ic_launcher.png")
    return written


def write_www(out: Path) -> list[str]:
    copied = []
    for src, name in www_pairs():
        if not src.exists():
            raise SystemExit(f"android/prepare.py: app/{name} is missing - the shell has nothing to carry")
        out.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, out / name)
        copied.append(name)
    return copied


def check() -> int:
    problems = []
    for src, name in www_pairs():
        if not src.exists():
            problems.append(f"app/{name} missing")
    stale = HERE / "www"
    if stale.exists():
        problems.append("android/www exists - the shell must carry no copy of the app; android/prepare.py makes it at build time")
    for f in sorted(HERE.rglob("mobile.html")):
        rel = f.relative_to(HERE)
        if rel.parts[0] in ("build", "dist"):
            continue            # generated by this script, and gitignored; nobody hand-wrote it
        problems.append(f"{f.relative_to(ROOT)} is a hand copy of the app")
    manifest = (HERE / "AndroidManifest.xml").read_text(encoding="utf-8")
    for ref in ("@mipmap/ic_launcher", "@xml/network"):
        if ref not in manifest:
            problems.append(f"AndroidManifest.xml no longer mentions {ref}")
    if problems:
        for p in problems:
            print(f"  FAIL {p}")
        print("android/prepare.py --check: " + "; ".join(problems))
        return 1
    carried = ", ".join(f"{n} {src.stat().st_size:,} B" for src, n in www_pairs())
    print(f"android/prepare.py --check: PASS - the build would carry {len(WWW)} files ({carried}) and "
          f"{len(ICON_SIZES)} icon buckets, all copied or drawn from app/, and no hand copy under android/")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("out", nargs="?", help="build directory to populate (omit with --check)")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    if a.check:
        return check()
    if not a.out:
        raise SystemExit("android/prepare.py: give a build directory, or --check")
    out = Path(a.out)
    # -A names the assets dir itself, so this lands at assets/www/... in the APK, which is what MainActivity opens
    copied = write_www(out / "pkg" / "www")
    icons = render_icons(out / "res")
    print(f"prepared {out}: assets/www=[{', '.join(copied)}] res=[{', '.join(icons)}]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
